title: Отчет для Министерства науки и высшего образования РФ
optionalCategoryIndex: true
supportedLanguages: []
properties: []
link:
  name: ReportMinobrCopy
  pathname: github.com/LyubovAsseyeva/ReportMinobrCopy/main/-
  logo: foni-papik-pro-krlx-p-kartinki-diagramma-na-prozrachnom-fone-1.png
  title: ReportMinobrCopy
  query: {}
  group: null
  code: ""
  style: null
  description: null
  order: 999999
  isCloning: false
  cloneCancelDisabled: false
  redirectOnClone: null
relatedLinks: []
name: ReportMinobrCopy
repositoryName: ReportMinobrCopy
sourceName: github.com
userInfo:
  mail: kitlove51@list.ru
  name: LyubovAsseyeva
  id: kitlove51@list.ru
docrootIsNoneExsistent: true
logo: foni-papik-pro-krlx-p-kartinki-diagramma-na-prozrachnom-fone-1.png
